---
title: "Explore Temporal Correlation of Sensors"
author: "Hayley Garment"
date: "6/29/2020"
output: html_document
---

In this file:

1. Look at temporal trends between sensors

Output

1. data/readable_station_codes.rds - names for station codes so easier to parse

```{r}
library(tidyverse)
library(readr)
library(lubridate)
library(tmap)
library(sf)
library(mapview)
library(broom)
library(rgdal)
library(sp)
library(forecast)
library(randomNames)
```


*Read Sensor Daily Data*
```{r}
sensor_data_tidy <- readRDS('data/sensor_data_tidy.rds') %>%
  filter(year(datetime) >= 2019)

sensor_data_tidy %>% distinct(station_serial)
```

*Calculate Daily Avg*
```{r}
daily_data <- sensor_data_tidy %>% 
  mutate(date = date(datetime)) %>% 
  group_by(date, station_serial) %>% 
  summarize(daily_mean_pm25 = mean(pm25_ug), n_readings = n()) %>% 
  ungroup() %>% 
  filter(n_readings >= 23) # each daily data has to be robustly calculated


ggplot(daily_data, aes(x=date, y=daily_mean_pm25)) + 
  geom_line() + facet_wrap(c('station_serial'))
```


*Recode station serials for my easy reading*
```{r}
#recode station serials into easier things
station_serials <- daily_data %>% distinct(station_serial) #21 stations
new_station_serials <- randomNames(21, ethnicity=1, which.names='first') #single words only pls

readable_station_codes <- cbind(station_serials, new_station_serials) %>% rename(station_codename = new_station_serials)

#saveRDS(readable_station_codes, 'data/readable_station_codes.rds')

readable_station_codes <- readRDS('data/readable_station_codes.rds')
daily_data_readable <- daily_data %>% left_join(., readable_station_codes) %>% dplyr::select(-station_serial, -n_readings)
```

*Create multivariate timeseries*
```{r}
# spread out the data so can correlate each of the sensors
daily_spread_data <- spread(daily_data_readable, station_codename, daily_mean_pm25)

#convert into a timeseries
ts_daily_data <- ts(daily_spread_data)
```

*Try acf covariate matrix?*
```{r}
# this I cannot read..
Acf(ts_daily_data, lag.max = 0, type="covariance", na.action = na.pass)
```

*Try ccf of series, tough with the gaps hmm*
```{r}
ccf(ts_daily_data[,"Aaron"], ts_daily_data[,"Bryan"])

```



```{r}
daily_spread_data %>% filter(month(date) == 6) %>% 

for (i in 1:21){
    for (j in 1:21){
      if (i != j) {
          ts_daily_data[,1+i]
          tslm_daily_avg <- tslm(ts_daily_data[,1+i] ~ Bryan, data = ts_daily_data)
      }

glance(tslm_daily_avg)$r.squared
    }
}


ccf(daily_data_readable$Aaron, daily_data_readable$Bryan)

ts_daily_data[,2]



```

