---
title: "Creating Spatial Files for Averages"
author: "Hayley Garment"
date: "6/19/2020"
output: html_document
---
In this file

1. Creating Shp file for each monthly average

Output:

1. data/geo_monthly_avgs/month_of_<2020-02-01> 
  # eg. shp files for avg per point in the month of feb 2020
  
2. data/monthly_avgs/month_of_<2020-02-01> 
  # eg. rds files of avg per point in month of feb 2020

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(readr)
library(lubridate)
library(tmap)
library(sf)
library(mapview)
library(tmap)
library(broom)
library(rgdal)
```

**1. Creating Shp file for each monthly average**

*Fetch data*
```{r}
monthly_means <- readRDS('data/sensor_means_by_month_over_650_readings.rds')
station_serials <- readRDS('data/stations_serial_num.rds')
```

*Join monthly means with lonlat data*
```{r}
station_serials <- station_serials %>% rename(station_serial = serial_number)

monthly_means_lonlat <- left_join(monthly_means, station_serials, by="station_serial") %>% dplyr::select(-Coordinate, -num_readings, -year, -month)
```

*Plot spatially to view*
```{r}
sf_monthly_means <- st_as_sf(monthly_means_lonlat, coords = c("lon", "lat"), crs = 4326) %>%
  st_transform(3414)

sf_monthly_means <- st_transform(sf_monthly_means, sf::st_crs("+proj=longlat +datum=WGS84"))

sf_monthly_means %>% filter(datetime == '2019-11-01') %>% 
  tm_shape() + tm_dots(col='monthly_avg_pm25')
```

*save as shp files*
```{r}
useable_months <- monthly_means %>% distinct(datetime) %>% arrange(datetime)

#for each month save?
for(i in 1:nrow(useable_months)) {
  month_to_use <- useable_months$datetime[[i]]
  
  means_for_month_to_use <- monthly_means_lonlat %>% filter(datetime == month_to_use)
  
  filename = paste("data/geo_monthly_avgs/month_of_", month_to_use, sep = '')
  filename_rds = paste("data/monthly_avgs/month_of_", month_to_use, ".rds", sep = '')
  
  # convert to spatial points data frame
  xy <- means_for_month_to_use[,c(5,4)] # lon then lat
  means_for_month_to_use_spatial <- SpatialPointsDataFrame(coords = xy, means_for_month_to_use)
  
  # write to shp file
  #writeOGR(means_for_month_to_use_spatial, dsn = filename, layer = "sensor_monthly_avg",
       #  driver = "ESRI Shapefile" )

  #write to rds file
  saveRDS(means_for_month_to_use, filename_rds)
}

```

```{r}
feb_2019_readings <- st_read("data/geo_monthly_avgs/month_of_2020-03-01/sensor_monthly_avg.shp")

st_as_sf(feb_2019_readings, crs= 3414) %>% tm_shape() + tm_dots(col='mnt__25')
```


